DROP TABLE IF EXISTS TRANSACAO;
DROP TABLE IF EXISTS CONTA;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME_COMPLETO VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    TIPO_INSTITUICAO VARCHAR(50) NOT NULL,
    NIVEL_ACADEMICO VARCHAR(50) NOT NULL,
    CURSO VARCHAR(100) NOT NULL
);

CREATE TABLE CONTA (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NUMERO_CONTA VARCHAR(20) NOT NULL UNIQUE,
    SALDO DECIMAL(10, 2) NOT NULL,
    TIPO_CONTA VARCHAR(50) NOT NULL,
    CLIENTE_ID BIGINT NOT NULL UNIQUE,
    
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)
);

CREATE TABLE TRANSACAO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    VALOR DECIMAL(10, 2) NOT NULL,
    TIPO_TRANSACAO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(255),
    
    CONTA_ORIGEM_ID BIGINT NOT NULL,
    CONTA_DESTINO_ID BIGINT,
    FOREIGN KEY (CONTA_ORIGEM_ID) REFERENCES CONTA(ID),
    FOREIGN KEY (CONTA_DESTINO_ID) REFERENCES CONTA(ID)
);